# Generated by Django 5.2.8 on 2026-07-31 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0026_update_telegram_tag_urls_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokFunnelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_endpoint', models.CharField(help_text='location.pathname лендинга, например /pasha_all', max_length=255, unique=True)),
                ('offer', models.CharField(help_text='Оффер/метка, например ell010005', max_length=255)),
                ('bot_url', models.CharField(help_text='Ссылка на бота', max_length=500)),
                ('bot_name', models.CharField(blank=True, default='', max_length=255)),
                ('pixel_code', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подключения'), ('active', 'Активна')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('warehouse_synced', models.BooleanField(default=False, help_text='Черновик воронки успешно записан в activation_data.tt_funnels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
